version: '3.7'

services:
  certbot:
    container_name: certbot
    image: certbot/dns-cloudflare
    command: >
      certonly
      --email $EMAIL
      --cert-name $DOMAIN
      --domains $DOMAIN
      --domains *.$DOMAIN
      --dns-cloudflare
      --dns-cloudflare-credentials /cloudflare.ini
      --agree-tos
      --keep-until-expiring
      --must-staple
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/letsencrypt:/etc/letsencrypt
      - ../cloudflare/cloudflare.ini:/cloudflare.ini:ro

  ddns:
    container_name: ddns
    image: pkoenig10/ddns-cloudflare
    environment:
      DOMAIN: $DOMAIN
      API_TOKEN: $CLOUDFLARE_API_TOKEN
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro

  backup:
    container_name: backup
    image: pkoenig10/dbxcli-backup
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR:/files
      - $SERVER_DIR/dbxcli:/root/.config/dbxcli
      - ../backup/backup.conf:/etc/backup/backup.conf:ro
