#!/usr/bin/with-contenv bash

set_config() {
    key="$1"
    value="$2"
    sed -i -r "s/(\"$key\": )[^,]*(\,)?/\1$value\2/g" /config/settings.json
}

IFS=":" read username password < <(echo $BASIC_AUTH | base64 -d)

set_config rpc-authentication-required true
set_config rpc-username \"$username\"
set_config rpc-password \"$password\"
